# app/products.py

products = [
    {
        '_id': "1",
        'name': "APPLE AIRPODS WIRELESS BLUETOOTH HEADPHONES",
        'image': "/image/airpods.jpg",
        'description': "Bluetooth technology lets you connect it with compatible devices wirelessly. High-quality AAC audio offers an immersive experience with a built-in microphone.",
        'brand': "Apple",
        'category': "Electronics",
        'price': 2900.99,
        'countInStock': 0,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': "2",
        'name': "ALEXA DOT 3RD GENERATION SMART SPEAKER WITH ALEXA",
        'image': "/image/alexa.jpg",
        'description': "Meet Echo Dot – Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small spaces.",
        'brand': "Amazon",
        'category': "Electronics",
        'price': 500.99,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': "3",
        'name': "CAMERA CANON DSLR 2000D WITH 18-55MM LENS",
        'image': "/image/camera.jpg",
        'description': "Canon DSLR 2000D camera with 18-55mm lens for high quality photos and videos.",
        'brand': "Canon",
        'category': "Electronics",
        'price': 85000.00,
        'countInStock': 8,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': "4",
        'name': "APPLE IPAD PRO 2026 MODEL",
        'image': "/image/ipad.webp",
        'description': "Apple iPad Pro model with advanced performance and retina display.",
        'brand': "Apple",
        'category': "Electronics",
        'price': 12100.00,
        'countInStock': 5,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': "5",
        'name': "APPLE WATCH SERIES 7",
        'image': "/image/watch.webp",
        'description': "Apple Watch Series 7 featuring fitness tracking and health monitoring features.",
        'brand': "Apple",
        'category': "Electronics",
        'price': 25000.00,
        'countInStock': 2,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': "6",
        'name': "SHOES NIKE AIR MAX 270 REACT SPORTS SHOES FOR MEN",
        'image': "/image/shoes.webp",
        'description': "Nike Air Max 270 React sports shoes designed for comfort and performance.",
        'brand': "Nike",
        'category': "Footwear",
        'price': 1500.00,
        'countInStock': 10,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        '_id': "7",
        'name': "SUNGLASSES RAY-BAN RB2132 NEW WAYFARER",
        'image': "/image/sunglasses.jpg",
        'description': "Ray-Ban RB2132 New Wayfarer sunglasses offering full UV protection.",
        'brand': "Ray-Ban",
        'category': "Accessories",
        'price': 1500.00,
        'countInStock': 0,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        '_id': "8",
        'name': "IPHONE 14 PRO MAX 5G SMARTPHONE",
        'image': "/image/iphone.avif",
        'description': "iPhone 14 Pro Max 5G smartphone with Dynamic Island and advanced camera system.",
        'brand': "Apple",
        'category': "Electronics",
        'price': 150000.00,
        'countInStock': 18,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        '_id': "9",
        'name': "APPLE MAGIC MOUSE 2 WIRELESS MOUSE",
        'image': "/image/mouse.jpg",
        'description': "Apple Magic Mouse 2 rechargeable wireless mouse with Multi-Touch surface.",
        'brand': "Apple",
        'category': "Electronics",
        'price': 15000.00,
        'countInStock': 0,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        '_id': "10",
        'name': "HP LAPTOP 15S-GR0011AU 15.6-INCH LAPTOP",
        'image': "/Image/hp-laptop.png",
        'description': "HP Laptop 15S-GR0011AU with 15.6-inch display and powerful performance.",
        'brand': "HP",
        'category': "Electronics",
        'price': 11000.00,
        'countInStock': 0,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        '_id': "11",
        'name': "SOUND BOX JBL FLIP 5 PORTABLE BLUETOOTH SPEAKER",
        'image': "/Image/soundbox.avif",
        'description': "JBL Flip 5 portable Bluetooth speaker with powerful sound and long battery life.",
        'brand': "JBL",
        'category': "Electronics",
        'price': 11000.00,
        'countInStock': 0,
        'rating': 5.8,
        'numReviews': 12,
    },
    {
        '_id': "12",
        'name': "FRIDGE LG 260 LITRES 2-DOOR REFRIGERATOR",
        'image': "/Image/frizz.webp",
        'description': "LG 260 litres 2-door refrigerator with advanced cooling technology.",
        'brand': "LG",
        'category': "Appliances",
        'price': 121000.00,
        'countInStock': 0,
        'rating': 5.8,
        'numReviews': 10,
    },
]